-- MySQL Script generated by MySQL Workbench
-- 05/22/16 18:05:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `eis` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eis`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `contrasena` VARCHAR(45) NULL COMMENT '',
  `publica` BLOB NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eis`.`archivo` (
  `idarchivo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(45) NULL COMMENT '',
  `fecha` VARCHAR(10) NULL COMMENT '',
  `link` VARCHAR(30) NULL COMMENT '',
  `idusuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idarchivo`, `idusuario`)  COMMENT '',
  INDEX `fk_archivo_usuario_idx` (`idusuario` ASC)  COMMENT '',
  CONSTRAINT `fk_archivo_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `eis`.`usuario` (`idusuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
